/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-ui/lib/alert')['default']
    ElBadge: typeof import('element-ui/lib/badge')['default']
    ElBreadcrumb: typeof import('element-ui/lib/breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-ui/lib/breadcrumb-item')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElColorPicker: typeof import('element-ui/lib/color-picker')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDescriptions: typeof import('element-ui/lib/descriptions')['default']
    ElDescriptionsItem: typeof import('element-ui/lib/descriptions-item')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElEmpty: typeof import('element-ui/lib/empty')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElInputNumber: typeof import('element-ui/lib/input-number')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTabPane: typeof import('element-ui/lib/tab-pane')['default']
    ElTabs: typeof import('element-ui/lib/tabs')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTree: typeof import('element-ui/lib/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
