UPDATE `sys_function_button`
SET `label` = CASE `code`
  WHEN 'button.system.page.create' THEN '新增页面'
  WHEN 'button.system.page.update' THEN '编辑页面'
  WHEN 'button.system.page.disable' THEN '停用页面'
  WHEN 'button.system.page.bind-api' THEN '配置页面接口'
  WHEN 'button.system.button.create' THEN '新增按钮'
  WHEN 'button.system.button.update' THEN '编辑按钮'
  WHEN 'button.system.button.disable' THEN '停用按钮'
  WHEN 'button.system.button.bind-api' THEN '绑定操作接口'
  WHEN 'button.system.user.create' THEN '新增用户'
  WHEN 'button.system.user.update' THEN '编辑用户'
  WHEN 'button.system.user.disable' THEN '停用用户'
  WHEN 'button.system.user.reset-password' THEN '重置密码'
  WHEN 'button.system.user.unlock' THEN '解锁用户'
  WHEN 'button.system.user.grant' THEN '分配角色'
  WHEN 'button.system.role.create' THEN '新增角色'
  WHEN 'button.system.role.update' THEN '编辑角色'
  WHEN 'button.system.role.disable' THEN '停用角色'
  WHEN 'button.system.role.grant' THEN '配置角色权限'
  WHEN 'button.system.role.delete' THEN '删除角色'
  WHEN 'button.system.api.create' THEN '新增接口'
  WHEN 'button.system.api.update' THEN '编辑接口'
  WHEN 'button.system.api.disable' THEN '停用接口'
  WHEN 'button.system.api.delete' THEN '删除接口'
  WHEN 'button.system.audit.export' THEN '导出审计日志'
  WHEN 'button.system.audit.integrity' THEN '校验日志完整性'
  WHEN 'button.system.approval.create' THEN '新建审批申请'
  WHEN 'button.system.approval.approve' THEN '审批通过'
  WHEN 'button.system.approval.execute' THEN '执行审批'
  WHEN 'button.system.approval.review' THEN '审计复核'
  WHEN 'button.system.data.update' THEN '调整数据范围'
  WHEN 'button.system.data.revoke' THEN '撤销数据范围'
  WHEN 'button.system.ops-ticket.create' THEN '新建应急工单'
  WHEN 'button.system.ops-ticket.update' THEN '编辑应急工单'
  WHEN 'button.system.ops-ticket.submit' THEN '提交应急工单'
  WHEN 'button.system.ops-ticket.approve' THEN '审批应急工单'
  WHEN 'button.system.ops-ticket.execute' THEN '执行应急工单'
  WHEN 'button.system.ops-ticket.review' THEN '复核应急工单'
  WHEN 'button.system.ops-ticket.cancel' THEN '取消应急工单'
  WHEN 'button.system.ops-ticket.evidence' THEN '补充工单证据'
  WHEN 'button.system.ops-ticket.executions' THEN '查看执行记录'
  WHEN 'button.system.operation-policy.manage' THEN '管理操作策略'
  WHEN 'button.system.operation-policy.activate' THEN '启用操作策略'
  WHEN 'button.system.operation-policy.disable' THEN '停用操作策略'
  ELSE `label`
END
WHERE `code` LIKE 'button.system.%';
