import { type RiskLevel } from './risk-policy.js'

export type DataFieldDefinition = {
  resource: string
  field: string
  name: string
  dataType: string
  relationResource?: string
  relationModel?: string
  relationField?: string
  riskLevel: RiskLevel
  writable?: boolean
  status?: 'ACTIVE' | 'DISABLED'
}

/** 数据字段目录。字段必须先登记，响应裁剪才允许输出。 */
export const DATA_FIELD_DEFINITIONS: readonly DataFieldDefinition[] = [
  {
    resource: 'system.user',
    field: 'userId',
    name: '用户 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.user',
    field: 'username',
    name: '登录账号',
    dataType: 'string',
    riskLevel: 'L2',
    writable: true,
  },
  {
    resource: 'system.user',
    field: 'displayName',
    name: '显示名称',
    dataType: 'string',
    riskLevel: 'L1',
    writable: true,
  },
  { resource: 'system.user', field: 'status', name: '状态', dataType: 'enum', riskLevel: 'L3' },
  {
    resource: 'system.user',
    field: 'failedLogins',
    name: '失败次数',
    dataType: 'number',
    riskLevel: 'L2',
  },
  {
    resource: 'system.user',
    field: 'lastLoginAt',
    name: '最后登录时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.user',
    field: 'createdAt',
    name: '创建时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.user',
    field: 'roles',
    name: '角色',
    dataType: 'array',
    relationResource: 'system.role',
    relationModel: 'Role',
    relationField: 'role',
    riskLevel: 'L2',
  },
  {
    resource: 'system.user',
    field: 'password',
    name: '密码',
    dataType: 'secret',
    riskLevel: 'L3',
    writable: true,
  },
  {
    resource: 'system.role',
    field: 'roleId',
    name: '角色 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.role',
    field: 'code',
    name: '角色编码',
    dataType: 'string',
    riskLevel: 'L3',
    writable: true,
  },
  {
    resource: 'system.role',
    field: 'name',
    name: '角色名称',
    dataType: 'string',
    riskLevel: 'L1',
    writable: true,
  },
  {
    resource: 'system.role',
    field: 'description',
    name: '角色描述',
    dataType: 'string',
    riskLevel: 'L1',
    writable: true,
  },
  {
    resource: 'system.role',
    field: 'roleType',
    name: '角色类型',
    dataType: 'enum',
    riskLevel: 'L3',
  },
  { resource: 'system.role', field: 'status', name: '角色状态', dataType: 'enum', riskLevel: 'L3' },
  {
    resource: 'system.role',
    field: 'createdAt',
    name: '创建时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.role',
    field: 'userCount',
    name: '用户数量',
    dataType: 'number',
    riskLevel: 'L2',
  },
  {
    resource: 'system.role',
    field: 'permissionIds',
    name: '权限 ID 列表',
    dataType: 'array',
    riskLevel: 'L3',
  },
  {
    resource: 'system.role',
    field: 'permissions',
    name: '权限列表',
    dataType: 'array',
    riskLevel: 'L3',
  },
  { resource: 'system.api', field: 'id', name: '接口 ID', dataType: 'string', riskLevel: 'L1' },
  {
    resource: 'system.api',
    field: 'code',
    name: '接口权限码',
    dataType: 'string',
    riskLevel: 'L3',
  },
  { resource: 'system.api', field: 'name', name: '接口名称', dataType: 'string', riskLevel: 'L1' },
  { resource: 'system.api', field: 'resource', name: '资源', dataType: 'string', riskLevel: 'L1' },
  { resource: 'system.api', field: 'action', name: '动作', dataType: 'string', riskLevel: 'L2' },
  {
    resource: 'system.api',
    field: 'method',
    name: '请求方法',
    dataType: 'string',
    riskLevel: 'L1',
  },
  { resource: 'system.api', field: 'path', name: '请求路径', dataType: 'string', riskLevel: 'L2' },
  { resource: 'system.api', field: 'status', name: '接口状态', dataType: 'enum', riskLevel: 'L3' },
  { resource: 'system.api', field: 'type', name: '权限类型', dataType: 'enum', riskLevel: 'L2' },
  {
    resource: 'system.api',
    field: '_count',
    name: '引用统计',
    dataType: 'object',
    riskLevel: 'L2',
  },
  { resource: 'system.audit', field: 'id', name: '审计 ID', dataType: 'string', riskLevel: 'L1' },
  {
    resource: 'system.audit',
    field: 'traceId',
    name: '链路 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'action',
    name: '操作动作',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'operationCode',
    name: '操作编码',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.audit',
    field: 'riskLevel',
    name: '风险等级',
    dataType: 'enum',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'resource',
    name: '资源',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'method',
    name: '请求方法',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'path',
    name: '请求路径',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.audit',
    field: 'result',
    name: '执行结果',
    dataType: 'enum',
    riskLevel: 'L1',
  },
  {
    resource: 'system.audit',
    field: 'statusCode',
    name: '状态码',
    dataType: 'number',
    riskLevel: 'L1',
  },
  { resource: 'system.audit', field: 'ip', name: 'IP 地址', dataType: 'string', riskLevel: 'L2' },
  {
    resource: 'system.audit',
    field: 'userAgent',
    name: '客户端信息',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.audit',
    field: 'detail',
    name: '审计详情',
    dataType: 'object',
    riskLevel: 'L3',
  },
  {
    resource: 'system.audit',
    field: 'integrityHash',
    name: '完整性摘要',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.audit',
    field: 'createdAt',
    name: '创建时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  { resource: 'system.audit', field: 'actor', name: '操作人', dataType: 'object', riskLevel: 'L2' },
  {
    resource: 'system.ops-ticket',
    field: 'id',
    name: '工单 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.ops-ticket',
    field: 'ticketNo',
    name: '工单编号',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.ops-ticket',
    field: 'type',
    name: '工单类型',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'status',
    name: '工单状态',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'riskLevel',
    name: '工单风险',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'title',
    name: '工单标题',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.ops-ticket',
    field: 'reason',
    name: '申请原因',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'targetType',
    name: '目标类型',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'targetId',
    name: '目标 ID',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'offlineBasis',
    name: '线下依据',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'identityVerification',
    name: '身份核验',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'offlineApprover',
    name: '线下审批人',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'offlineReviewer',
    name: '线下复核人',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'externalRef',
    name: '外部关联号',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'requestedBy',
    name: '申请人',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'approvedBy',
    name: '审批人',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'executedBy',
    name: '执行人',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'reviewedBy',
    name: '复核人',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.ops-ticket',
    field: 'createdAt',
    name: '创建时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.ops-ticket',
    field: 'updatedAt',
    name: '更新时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.ops-ticket',
    field: 'evidence',
    name: '工单证据',
    dataType: 'array',
    riskLevel: 'L3',
  },
  {
    resource: 'system.ops-ticket',
    field: 'executions',
    name: '执行记录',
    dataType: 'array',
    riskLevel: 'L3',
  },
  {
    resource: 'system.permission',
    field: 'id',
    name: '权限 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.permission',
    field: 'code',
    name: '权限码',
    dataType: 'string',
    riskLevel: 'L3',
  },
  {
    resource: 'system.permission',
    field: 'name',
    name: '权限名称',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.permission',
    field: 'resource',
    name: '资源标识',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.permission',
    field: 'action',
    name: '操作动作',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.permission',
    field: 'type',
    name: '权限类型',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.permission',
    field: 'requiredRoleType',
    name: '要求角色类型',
    dataType: 'enum',
    riskLevel: 'L3',
  },
  {
    resource: 'system.permission',
    field: 'status',
    name: '权限状态',
    dataType: 'enum',
    riskLevel: 'L3',
  },
  {
    resource: 'system.permission',
    field: 'method',
    name: '请求方法',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.permission',
    field: 'path',
    name: '请求路径',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.permission',
    field: 'permissionIds',
    name: '关联权限 ID',
    dataType: 'array',
    riskLevel: 'L3',
  },
  {
    resource: 'system.approval',
    field: 'id',
    name: '审批 ID',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'requestNo',
    name: '申请单号',
    dataType: 'string',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'kind',
    name: '审批类型',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'status',
    name: '审批状态',
    dataType: 'enum',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'reason',
    name: '申请原因',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'expiresAt',
    name: '失效时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'createdAt',
    name: '创建时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'updatedAt',
    name: '更新时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'applicant',
    name: '申请人',
    dataType: 'object',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'approver',
    name: '审批人',
    dataType: 'object',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'executor',
    name: '执行人',
    dataType: 'object',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'reviewer',
    name: '复核人',
    dataType: 'object',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'payload',
    name: '申请内容',
    dataType: 'object',
    riskLevel: 'L3',
  },
  {
    resource: 'system.approval',
    field: 'approvedAt',
    name: '审批时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'executedAt',
    name: '执行时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'reviewedAt',
    name: '复核时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.approval',
    field: 'approvalNote',
    name: '审批意见',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'executionNote',
    name: '执行说明',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.approval',
    field: 'reviewNote',
    name: '复核意见',
    dataType: 'string',
    riskLevel: 'L2',
  },
  {
    resource: 'system.health',
    field: 'status',
    name: '系统状态',
    dataType: 'enum',
    riskLevel: 'L1',
  },
  {
    resource: 'system.health',
    field: 'checkedAt',
    name: '检查时间',
    dataType: 'datetime',
    riskLevel: 'L1',
  },
  {
    resource: 'system.health',
    field: 'services',
    name: '服务状态',
    dataType: 'array',
    riskLevel: 'L1',
  },
]

export const DATA_FIELD_PERMISSIONS = DATA_FIELD_DEFINITIONS.flatMap((field) => {
  const prefix = `${field.resource}.field.${field.field}`
  const permissions = [
    { code: `${prefix}.read`, name: `${field.name}查看`, action: `field.${field.field}.read` },
  ]
  if (field.writable)
    permissions.push({
      code: `${prefix}.write`,
      name: `${field.name}修改`,
      action: `field.${field.field}.write`,
    })
  return permissions
})
